import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedEntities1781512351909 implements MigrationInterface {
    name = 'AddedEntities1781512351909'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "otp_verifications" ("id" BIGSERIAL NOT NULL, "user_id" bigint, "target" character varying NOT NULL, "target_type" character varying NOT NULL, "purpose" character varying NOT NULL, "otp_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "verified_at" TIMESTAMP WITH TIME ZONE, "attempt_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" bigint, CONSTRAINT "PK_91d17e75ac3182dba6701869b39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_otp_target_purpose_expires" ON "otp_verifications" ("target", "purpose", "expires_at") `);
        await queryRunner.query(`CREATE TYPE "public"."discount_type" AS ENUM('fixed_amount', 'percentage')`);
        await queryRunner.query(`CREATE TYPE "public"."promotion_status" AS ENUM('draft', 'active', 'paused', 'expired', 'archived')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" BIGSERIAL NOT NULL, "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "branch_id" bigint, "discount_type" "public"."discount_type" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "max_discount_amount" numeric(10,2), "min_order_amount" numeric(10,2), "usage_limit_total" integer, "usage_limit_per_customer" integer, "used_count" integer NOT NULL DEFAULT '0', "starts_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ends_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."promotion_status" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branchId" bigint, CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_promotions_status_dates" ON "promotions" ("status", "starts_at", "ends_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_promotions_branch_id" ON "promotions" ("branch_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_promotions_code_unique" ON "promotions" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."discount_code_status" AS ENUM('active', 'inactive', 'expired', 'archived')`);
        await queryRunner.query(`CREATE TABLE "discount_codes" ("id" BIGSERIAL NOT NULL, "promotion_id" bigint NOT NULL, "code" character varying(100) NOT NULL, "usage_limit_total" integer, "usage_limit_per_customer" integer, "used_count" integer NOT NULL DEFAULT '0', "status" "public"."discount_code_status" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "promotionId" bigint, CONSTRAINT "PK_c0170a28d937472e9ce50fdce17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_discount_codes_status" ON "discount_codes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_discount_codes_promotion_id" ON "discount_codes" ("promotion_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_discount_codes_code_unique" ON "discount_codes" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."booking_status" AS ENUM('pending_payment', 'confirmed', 'checked_in', 'in_service', 'completed', 'cancelled', 'no_show', 'rescheduled', 'transferred')`);
        await queryRunner.query(`CREATE TYPE "public"."booking_source" AS ENUM('online', 'staff', 'walk_in')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" BIGSERIAL NOT NULL, "customer_id" bigint NOT NULL, "branch_id" bigint NOT NULL, "technician_id" bigint, "discount_code_id" bigint, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."booking_status" NOT NULL DEFAULT 'pending_payment', "source" "public"."booking_source" NOT NULL DEFAULT 'online', "subtotal_amount" numeric(10,2) NOT NULL DEFAULT '0', "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "deposit_required_amount" numeric(10,2) NOT NULL DEFAULT '0', "paid_amount" numeric(10,2) NOT NULL DEFAULT '0', "remaining_amount" numeric(10,2) NOT NULL DEFAULT '0', "notes" text, "cancel_reason" text, "transferred_from_branch_id" bigint, "rescheduled_from_booking_id" bigint, "created_by" bigint, "checked_in_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "branchId" bigint, "technicianId" bigint, "discountCodeId" bigint, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_branch_status_time" ON "bookings" ("branch_id", "status", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_customer_time" ON "bookings" ("customer_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_technician_time" ON "bookings" ("technician_id", "start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_branch_time" ON "bookings" ("branch_id", "start_time", "end_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_status" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_technician_id" ON "bookings" ("technician_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_branch_id" ON "bookings" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_customer_id" ON "bookings" ("customer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status" AS ENUM('draft', 'issued', 'partially_paid', 'paid', 'voided', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" BIGSERIAL NOT NULL, "invoice_number" character varying(100) NOT NULL, "booking_id" bigint, "customer_id" bigint NOT NULL, "branch_id" bigint NOT NULL, "status" "public"."invoice_status" NOT NULL DEFAULT 'draft', "subtotal_amount" numeric(10,2) NOT NULL, "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "paid_amount" numeric(10,2) NOT NULL DEFAULT '0', "remaining_amount" numeric(10,2) NOT NULL DEFAULT '0', "issued_at" TIMESTAMP WITH TIME ZONE, "voided_at" TIMESTAMP WITH TIME ZONE, "created_by" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "bookingId" bigint, "customerId" bigint, "branchId" bigint, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_customer_created" ON "invoices" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_branch_issued" ON "invoices" ("branch_id", "issued_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_status" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_branch_id" ON "invoices" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_customer_id" ON "invoices" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_booking_id" ON "invoices" ("booking_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invoices_number_unique" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE TYPE "public"."treatment_course_status" AS ENUM('active', 'completed', 'expired', 'cancelled', 'paused')`);
        await queryRunner.query(`CREATE TABLE "treatment_courses" ("id" BIGSERIAL NOT NULL, "customer_id" bigint NOT NULL, "service_id" bigint NOT NULL, "branch_id" bigint, "purchase_invoice_id" bigint, "total_sessions" integer NOT NULL, "used_sessions" integer NOT NULL DEFAULT '0', "remaining_sessions" integer NOT NULL, "status" "public"."treatment_course_status" NOT NULL DEFAULT 'active', "started_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "serviceId" bigint, "branchId" bigint, "purchaseInvoiceId" bigint, CONSTRAINT "PK_b473432055fac8c6a8fa36419ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_courses_expires_at" ON "treatment_courses" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_courses_branch_id" ON "treatment_courses" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_courses_service_id" ON "treatment_courses" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_courses_customer_status" ON "treatment_courses" ("customer_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."treatment_session_status" AS ENUM('planned', 'booked', 'in_progress', 'completed', 'skipped', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "treatment_sessions" ("id" BIGSERIAL NOT NULL, "treatment_course_id" bigint NOT NULL, "booking_id" bigint, "service_id" bigint NOT NULL, "session_number" integer NOT NULL, "status" "public"."treatment_session_status" NOT NULL DEFAULT 'planned', "staff_id" bigint, "progress_note" text, "before_images" jsonb, "after_images" jsonb, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "treatmentCourseId" bigint, "bookingId" bigint, "serviceId" bigint, "staffId" bigint, CONSTRAINT "PK_f301891fd97dab91f2c0fe18614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_sessions_staff_id" ON "treatment_sessions" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_sessions_booking_id" ON "treatment_sessions" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_sessions_course_id" ON "treatment_sessions" ("treatment_course_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_treatment_sessions_course_number" ON "treatment_sessions" ("treatment_course_id", "session_number") `);
        await queryRunner.query(`CREATE TYPE "public"."review_status" AS ENUM('pending', 'published', 'hidden', 'removed')`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" BIGSERIAL NOT NULL, "customer_id" bigint NOT NULL, "booking_id" bigint NOT NULL, "service_id" bigint, "branch_id" bigint NOT NULL, "technician_id" bigint, "rating" integer NOT NULL, "comment" text, "status" "public"."review_status" NOT NULL DEFAULT 'published', "reply_text" text, "replied_by" bigint, "replied_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "bookingId" bigint, "serviceId" bigint, "branchId" bigint, "technicianId" bigint, "repliedByUserId" bigint, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_technician_rating" ON "reviews" ("technician_id", "rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_branch_rating" ON "reviews" ("branch_id", "rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_rating" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_technician_id" ON "reviews" ("technician_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_service_id" ON "reviews" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reviews_branch_id" ON "reviews" ("branch_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_reviews_customer_booking_service" ON "reviews" ("customer_id", "booking_id", "service_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_type" AS ENUM('deposit', 'full_payment', 'remaining_payment')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method" AS ENUM('cash', 'card', 'bank_transfer', 'e_wallet', 'online_gateway')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status" AS ENUM('pending', 'paid', 'failed', 'cancelled', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" BIGSERIAL NOT NULL, "invoice_id" bigint, "booking_id" bigint, "customer_id" bigint NOT NULL, "branch_id" bigint NOT NULL, "payment_type" "public"."payment_type" NOT NULL, "payment_method" "public"."payment_method" NOT NULL, "status" "public"."payment_status" NOT NULL DEFAULT 'pending', "amount" numeric(10,2) NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "received_by" bigint, "refunded_amount" numeric(10,2) NOT NULL DEFAULT '0', "refund_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "invoiceId" bigint, "bookingId" bigint, "customerId" bigint, "branchId" bigint, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payments_customer_created" ON "payments" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_branch_paid" ON "payments" ("branch_id", "paid_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_branch_id" ON "payments" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_customer_id" ON "payments" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_booking_id" ON "payments" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_invoice_id" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."schedule_request_type" AS ENUM('work_shift', 'day_off', 'leave')`);
        await queryRunner.query(`CREATE TYPE "public"."approval_status" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "schedule_requests" ("id" BIGSERIAL NOT NULL, "staff_id" bigint NOT NULL, "branch_id" bigint NOT NULL, "request_type" "public"."schedule_request_type" NOT NULL, "requested_start" TIMESTAMP WITH TIME ZONE NOT NULL, "requested_end" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."approval_status" NOT NULL DEFAULT 'pending', "reason" text, "reviewed_by" bigint, "reviewed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "staffId" bigint, "branchId" bigint, "reviewerId" bigint, CONSTRAINT "PK_73f638c7d4666f6518f4c0ecadf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_schedule_requests_staff_time" ON "schedule_requests" ("staff_id", "requested_start", "requested_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_schedule_requests_reviewed_by" ON "schedule_requests" ("reviewed_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_schedule_requests_status" ON "schedule_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_schedule_requests_branch_id" ON "schedule_requests" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_schedule_requests_staff_id" ON "schedule_requests" ("staff_id") `);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" BIGSERIAL NOT NULL, "invoice_id" bigint NOT NULL, "service_id" bigint, "description" text NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "line_total" numeric(10,2) NOT NULL, "invoiceId" bigint, "serviceId" bigint, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_items_service_id" ON "invoice_items" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_items_invoice_id" ON "invoice_items" ("invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_item_status" AS ENUM('active', 'inactive', 'archived')`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" BIGSERIAL NOT NULL, "sku" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "unit" character varying(50) NOT NULL, "category" character varying(100), "min_stock_level" numeric(10,3), "status" "public"."inventory_item_status" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_items_category" ON "inventory_items" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_items_status" ON "inventory_items" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_inventory_items_sku_unique" ON "inventory_items" ("sku") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transaction_type" AS ENUM('import', 'consume', 'adjustment_increase', 'adjustment_decrease', 'stock_check_correction', 'damaged', 'expired', 'return')`);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" BIGSERIAL NOT NULL, "branch_id" bigint NOT NULL, "inventory_item_id" bigint NOT NULL, "transaction_type" "public"."inventory_transaction_type" NOT NULL, "quantity_delta" numeric(10,3) NOT NULL, "quantity_after" numeric(10,3), "booking_id" bigint, "service_id" bigint, "staff_id" bigint, "reason" text, "created_by" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branchId" bigint, "inventoryItemId" bigint, "bookingId" bigint, "serviceId" bigint, "staffId" bigint, "createdByUserId" bigint, CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_branch_item_created" ON "inventory_transactions" ("branch_id", "inventory_item_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_created_by" ON "inventory_transactions" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_service_id" ON "inventory_transactions" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_booking_id" ON "inventory_transactions" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_type" ON "inventory_transactions" ("transaction_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_item_id" ON "inventory_transactions" ("inventory_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_inv_tx_branch_id" ON "inventory_transactions" ("branch_id") `);
        await queryRunner.query(`CREATE TABLE "branch_inventory" ("id" BIGSERIAL NOT NULL, "branch_id" bigint NOT NULL, "inventory_item_id" bigint NOT NULL, "current_quantity" numeric(10,3) NOT NULL DEFAULT '0', "reserved_quantity" numeric(10,3) NOT NULL DEFAULT '0', "last_transaction_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branchId" bigint, "inventoryItemId" bigint, CONSTRAINT "PK_c23766e60c8ee7150fdaaff3620" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_branch_inventory_branch_qty" ON "branch_inventory" ("branch_id", "current_quantity") `);
        await queryRunner.query(`CREATE INDEX "IDX_branch_inventory_item_id" ON "branch_inventory" ("inventory_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_branch_inventory_branch_id" ON "branch_inventory" ("branch_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branch_inventory_branch_item" ON "branch_inventory" ("branch_id", "inventory_item_id") `);
        await queryRunner.query(`CREATE TABLE "health_records" ("id" BIGSERIAL NOT NULL, "customer_id" bigint NOT NULL, "branch_id" bigint, "allergies" text, "medical_conditions" text, "skin_type" character varying(100), "pregnancy_status" character varying(100), "contraindications" text, "notes" text, "created_by" bigint NOT NULL, "updated_by" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "branchId" bigint, "createdByUserId" bigint, "updatedByUserId" bigint, CONSTRAINT "PK_adbd60dda85d616da89ba3f8270" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_health_records_branch_id" ON "health_records" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_health_records_customer_id" ON "health_records" ("customer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."conversation_status" AS ENUM('open', 'assigned', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" BIGSERIAL NOT NULL, "customer_id" bigint, "branch_id" bigint, "assigned_staff_id" bigint, "guest_name" character varying(255), "guest_phone" character varying(20), "guest_email" character varying(255), "subject" character varying(255), "status" "public"."conversation_status" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "branchId" bigint, "assignedStaffId" bigint, CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_branch_status" ON "conversations" ("branch_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_status" ON "conversations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_assigned_staff_id" ON "conversations" ("assigned_staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_branch_id" ON "conversations" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_customer_id" ON "conversations" ("customer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."sender_type" AS ENUM('guest', 'customer', 'staff', 'system')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" BIGSERIAL NOT NULL, "conversation_id" bigint NOT NULL, "sender_user_id" bigint, "sender_type" "public"."sender_type" NOT NULL, "message" text NOT NULL, "attachments" jsonb, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "conversationId" bigint, "senderUserId" bigint, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_messages_conversation_created" ON "messages" ("conversation_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_sender_user_id" ON "messages" ("sender_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_conversation_id" ON "messages" ("conversation_id") `);
        await queryRunner.query(`CREATE TYPE "public"."complaint_status" AS ENUM('open', 'in_progress', 'resolved', 'rejected', 'closed')`);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" BIGSERIAL NOT NULL, "customer_id" bigint NOT NULL, "branch_id" bigint NOT NULL, "booking_id" bigint, "title" character varying(255) NOT NULL, "description" text NOT NULL, "status" "public"."complaint_status" NOT NULL DEFAULT 'open', "assigned_to" bigint, "resolution_note" text, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" bigint, "branchId" bigint, "bookingId" bigint, "assignedUserId" bigint, CONSTRAINT "PK_4b7566a2a489c2cc7c12ed076ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_customer_created" ON "complaints" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_branch_status" ON "complaints" ("branch_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_status" ON "complaints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_assigned_to" ON "complaints" ("assigned_to") `);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_branch_id" ON "complaints" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_complaints_customer_id" ON "complaints" ("customer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."staff_status" AS ENUM('active', 'on_leave', 'inactive', 'transferred')`);
        await queryRunner.query(`CREATE TABLE "branch_staff" ("id" BIGSERIAL NOT NULL, "branch_id" bigint NOT NULL, "user_id" bigint NOT NULL, "staff_code" character varying(50), "position" character varying(100) NOT NULL, "status" "public"."staff_status" NOT NULL DEFAULT 'active', "start_date" date NOT NULL, "end_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branchId" bigint, "userId" bigint, CONSTRAINT "PK_e9d2640fc540b726256b005df91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_branch_staff_user_status" ON "branch_staff" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_branch_staff_branch_status" ON "branch_staff" ("branch_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branch_staff_branch_code" ON "branch_staff" ("branch_id", "staff_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branch_staff_branch_user" ON "branch_staff" ("branch_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "branch_opening_hours" ("id" BIGSERIAL NOT NULL, "branch_id" bigint NOT NULL, "day_of_week" integer NOT NULL, "open_time" TIME NOT NULL, "close_time" TIME NOT NULL, "is_closed" boolean NOT NULL DEFAULT false, "branchId" bigint, CONSTRAINT "PK_811cbd6580dbe074a4b89b83312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branch_opening_hours_branch_day" ON "branch_opening_hours" ("branch_id", "day_of_week") `);
        await queryRunner.query(`CREATE TABLE "booking_slot_configs" ("id" BIGSERIAL NOT NULL, "branch_id" bigint NOT NULL, "day_of_week" integer NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "slot_minutes" integer NOT NULL, "max_bookings" integer NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branchId" bigint, CONSTRAINT "PK_fb0831e4eb484ada5ce9d1e82ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_slot_config_branch_effective" ON "booking_slot_configs" ("branch_id", "effective_from", "effective_to") `);
        await queryRunner.query(`CREATE INDEX "IDX_slot_config_branch_day_time" ON "booking_slot_configs" ("branch_id", "day_of_week", "start_time", "end_time") `);
        await queryRunner.query(`CREATE TABLE "booking_services" ("id" BIGSERIAL NOT NULL, "booking_id" bigint NOT NULL, "service_id" bigint NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "duration_minutes" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "final_amount" numeric(10,2) NOT NULL, "bookingId" bigint, "serviceId" bigint, CONSTRAINT "PK_8997bf4d0728c8740c87694d59a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_booking_services_service_id" ON "booking_services" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_services_booking_id" ON "booking_services" ("booking_id") `);
        await queryRunner.query(`ALTER TYPE "public"."service_status" RENAME TO "service_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."service_status" AS ENUM('draft', 'active', 'inactive', 'archived')`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" TYPE "public"."service_status" USING "status"::"text"::"public"."service_status"`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."service_status_old"`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD CONSTRAINT "FK_fec02639ae24944c2122230ae4c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_f0c22277696f66bfefe47f6c84c" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_901a674605520b862ab90d4e291" FOREIGN KEY ("promotionId") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64de318a01c502530b1e32692fd" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0004f78587144778e6594453737" FOREIGN KEY ("technicianId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_6163d5bf8de921b15bd88c0a4b1" FOREIGN KEY ("discountCodeId") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_eca01fda44679cc1c342822e01b" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_cc476907858590c95b285c1eeb8" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_28850a5ffe7a43c4a584fb0c751" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_70072135e60ecccce7e23630a0e" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_147a11ecdcf0d0fa523a2f195d5" FOREIGN KEY ("purchaseInvoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_627678e9a2a3ac157d5bcbe62e9" FOREIGN KEY ("treatmentCourseId") REFERENCES "treatment_courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_77630101d477abe99bced10fe07" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_6840e49db66ab441fd35ca76f2e" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_a1a11c710e26dd1d28becc355f9" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6d99bdfa69280ede313699fab92" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9563540c43639a0669f68e8ebe3" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_dcb5f7aa1bf056a73208733ce79" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c54130ec9165473fccdde38b77d" FOREIGN KEY ("technicianId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a9c849393e14bd7bde111a833f1" FOREIGN KEY ("repliedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_824be6feda5e655c49c4e0c534b" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_827d04dd3e917e88271d43e664b" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_b430b694818883cea5b8f9938de" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_6508dbe7e688da45f65891652c9" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_1efcd05ef30e6f492c31538e8e2" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_e8af4023b5bfefa942b83773cbb" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_8b7abfe15fc668ef7c251b14aac" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_4db761e1d6856cadc6f523b955d" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_0cff72bb05e6063ed8f06036af4" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_09acaaef552e6fbc1987676f5df" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_af69bc0caf9302582f7930b6547" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_05ae66836bda06ca1048e696d01" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_58844b23b9aefcb7ec2bc2863dc" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_2506f1cb7997e171e2ff1042dcb" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_b239989be631aac1fec54463db8" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_11ef1fb7d5b79c48c712e801c13" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_459d7c3ebd2d350cb2258dd49f4" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_358993f269a7b0c336ebca6f562" FOREIGN KEY ("updatedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_5a4866f304edf4591ad785d34a4" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_36a177d087ea05c7eb5cf618da2" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_7e00ff5bf38a3c03faea05a9d7c" FOREIGN KEY ("assignedStaffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2868049bbe999cdf09aed764400" FOREIGN KEY ("senderUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_3860fae46824a024252a3875769" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_2f071ace1c076ef1c0bc55b1d46" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_4382543bfea88b0b8cb2fa13372" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_4c5b92dda61206dd793e4376a9e" FOREIGN KEY ("assignedUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_3c563aa16f6c0d2807f80f6eb0f" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_a641cc2cf997b72d86e73f0fff8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD CONSTRAINT "FK_cb752f90241fb5cdd151be092ee" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD CONSTRAINT "FK_597fe37979414942a48526a9dbc" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_9a9d697fbd86c5285ed1662c7c7" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_6670d3e3d8c010bcdc3bc7a4be2" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_6670d3e3d8c010bcdc3bc7a4be2"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_9a9d697fbd86c5285ed1662c7c7"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP CONSTRAINT "FK_597fe37979414942a48526a9dbc"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP CONSTRAINT "FK_cb752f90241fb5cdd151be092ee"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_a641cc2cf997b72d86e73f0fff8"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_3c563aa16f6c0d2807f80f6eb0f"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_4c5b92dda61206dd793e4376a9e"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_4382543bfea88b0b8cb2fa13372"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_2f071ace1c076ef1c0bc55b1d46"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_3860fae46824a024252a3875769"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2868049bbe999cdf09aed764400"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_7e00ff5bf38a3c03faea05a9d7c"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_36a177d087ea05c7eb5cf618da2"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_5a4866f304edf4591ad785d34a4"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_358993f269a7b0c336ebca6f562"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_459d7c3ebd2d350cb2258dd49f4"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_11ef1fb7d5b79c48c712e801c13"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_b239989be631aac1fec54463db8"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_2506f1cb7997e171e2ff1042dcb"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_58844b23b9aefcb7ec2bc2863dc"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_05ae66836bda06ca1048e696d01"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_af69bc0caf9302582f7930b6547"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_09acaaef552e6fbc1987676f5df"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_0cff72bb05e6063ed8f06036af4"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_4db761e1d6856cadc6f523b955d"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_8b7abfe15fc668ef7c251b14aac"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_e8af4023b5bfefa942b83773cbb"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_1efcd05ef30e6f492c31538e8e2"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_6508dbe7e688da45f65891652c9"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_b430b694818883cea5b8f9938de"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_827d04dd3e917e88271d43e664b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_824be6feda5e655c49c4e0c534b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a9c849393e14bd7bde111a833f1"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c54130ec9165473fccdde38b77d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_dcb5f7aa1bf056a73208733ce79"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9563540c43639a0669f68e8ebe3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6d99bdfa69280ede313699fab92"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_a1a11c710e26dd1d28becc355f9"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_6840e49db66ab441fd35ca76f2e"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_77630101d477abe99bced10fe07"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_627678e9a2a3ac157d5bcbe62e9"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_147a11ecdcf0d0fa523a2f195d5"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_70072135e60ecccce7e23630a0e"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_28850a5ffe7a43c4a584fb0c751"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_cc476907858590c95b285c1eeb8"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_eca01fda44679cc1c342822e01b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_6163d5bf8de921b15bd88c0a4b1"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0004f78587144778e6594453737"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64de318a01c502530b1e32692fd"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_901a674605520b862ab90d4e291"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_f0c22277696f66bfefe47f6c84c"`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP CONSTRAINT "FK_fec02639ae24944c2122230ae4c"`);
        await queryRunner.query(`CREATE TYPE "public"."service_status_old" AS ENUM('active', 'inactive', 'archived')`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" TYPE "public"."service_status_old" USING "status"::"text"::"public"."service_status_old"`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."service_status"`);
        await queryRunner.query(`ALTER TYPE "public"."service_status_old" RENAME TO "service_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_services_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_services_service_id"`);
        await queryRunner.query(`DROP TABLE "booking_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_slot_config_branch_day_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_slot_config_branch_effective"`);
        await queryRunner.query(`DROP TABLE "booking_slot_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_opening_hours_branch_day"`);
        await queryRunner.query(`DROP TABLE "branch_opening_hours"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_staff_branch_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_staff_branch_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_staff_branch_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_staff_user_status"`);
        await queryRunner.query(`DROP TABLE "branch_staff"`);
        await queryRunner.query(`DROP TYPE "public"."staff_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_assigned_to"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_branch_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_complaints_customer_created"`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`DROP TYPE "public"."complaint_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_conversation_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_sender_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_conversation_created"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."sender_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_assigned_staff_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_branch_status"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversation_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_health_records_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_health_records_branch_id"`);
        await queryRunner.query(`DROP TABLE "health_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_inventory_branch_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_inventory_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_inventory_item_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branch_inventory_branch_qty"`);
        await queryRunner.query(`DROP TABLE "branch_inventory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_item_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_service_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inv_tx_branch_item_created"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transaction_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_items_sku_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_items_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_items_category"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_item_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_items_invoice_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_items_service_id"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_schedule_requests_staff_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_schedule_requests_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_schedule_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_schedule_requests_reviewed_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_schedule_requests_staff_time"`);
        await queryRunner.query(`DROP TABLE "schedule_requests"`);
        await queryRunner.query(`DROP TYPE "public"."approval_status"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_request_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_invoice_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_branch_paid"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_customer_created"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_customer_booking_service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_service_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_technician_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_rating"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_branch_rating"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reviews_technician_rating"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TYPE "public"."review_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_sessions_course_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_sessions_course_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_sessions_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_sessions_staff_id"`);
        await queryRunner.query(`DROP TABLE "treatment_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."treatment_session_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_courses_customer_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_courses_service_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_courses_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_courses_expires_at"`);
        await queryRunner.query(`DROP TABLE "treatment_courses"`);
        await queryRunner.query(`DROP TYPE "public"."treatment_course_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_number_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_branch_issued"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_customer_created"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_technician_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_branch_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_technician_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_customer_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_branch_status_time"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."booking_source"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_discount_codes_code_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_discount_codes_promotion_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_discount_codes_status"`);
        await queryRunner.query(`DROP TABLE "discount_codes"`);
        await queryRunner.query(`DROP TYPE "public"."discount_code_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_promotions_code_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_promotions_branch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_promotions_status_dates"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotion_status"`);
        await queryRunner.query(`DROP TYPE "public"."discount_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otp_target_purpose_expires"`);
        await queryRunner.query(`DROP TABLE "otp_verifications"`);
    }

}
