import { MigrationInterface, QueryRunner } from 'typeorm';

// Drops the spurious camelCase FK columns that TypeORM auto-generated due to
// missing @JoinColumn decorators on all @ManyToOne relations, and moves the FK
// constraints onto the correct snake_case columns that were already present.
export class FixDuplicateFkColumns1781600000000 implements MigrationInterface {
    name = 'FixDuplicateFkColumns1781600000000';

    public async up(queryRunner: QueryRunner): Promise<void> {
        // ── Step 1: Drop FK constraints that lived on the spurious camelCase columns ──

        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_6670d3e3d8c010bcdc3bc7a4be2"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_9a9d697fbd86c5285ed1662c7c7"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP CONSTRAINT "FK_597fe37979414942a48526a9dbc"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP CONSTRAINT "FK_cb752f90241fb5cdd151be092ee"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_a641cc2cf997b72d86e73f0fff8"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_3c563aa16f6c0d2807f80f6eb0f"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_4c5b92dda61206dd793e4376a9e"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_4382543bfea88b0b8cb2fa13372"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_2f071ace1c076ef1c0bc55b1d46"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_3860fae46824a024252a3875769"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2868049bbe999cdf09aed764400"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_7e00ff5bf38a3c03faea05a9d7c"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_36a177d087ea05c7eb5cf618da2"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_5a4866f304edf4591ad785d34a4"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_358993f269a7b0c336ebca6f562"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_459d7c3ebd2d350cb2258dd49f4"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_11ef1fb7d5b79c48c712e801c13"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_b239989be631aac1fec54463db8"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_2506f1cb7997e171e2ff1042dcb"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_58844b23b9aefcb7ec2bc2863dc"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_05ae66836bda06ca1048e696d01"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_af69bc0caf9302582f7930b6547"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_09acaaef552e6fbc1987676f5df"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_0cff72bb05e6063ed8f06036af4"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_4db761e1d6856cadc6f523b955d"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_8b7abfe15fc668ef7c251b14aac"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_e8af4023b5bfefa942b83773cbb"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_1efcd05ef30e6f492c31538e8e2"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_6508dbe7e688da45f65891652c9"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_b430b694818883cea5b8f9938de"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_827d04dd3e917e88271d43e664b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_824be6feda5e655c49c4e0c534b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a9c849393e14bd7bde111a833f1"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c54130ec9165473fccdde38b77d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_dcb5f7aa1bf056a73208733ce79"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9563540c43639a0669f68e8ebe3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6d99bdfa69280ede313699fab92"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_a1a11c710e26dd1d28becc355f9"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_6840e49db66ab441fd35ca76f2e"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_77630101d477abe99bced10fe07"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_627678e9a2a3ac157d5bcbe62e9"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_147a11ecdcf0d0fa523a2f195d5"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_70072135e60ecccce7e23630a0e"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_28850a5ffe7a43c4a584fb0c751"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_cc476907858590c95b285c1eeb8"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_eca01fda44679cc1c342822e01b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_6163d5bf8de921b15bd88c0a4b1"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0004f78587144778e6594453737"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64de318a01c502530b1e32692fd"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_901a674605520b862ab90d4e291"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_f0c22277696f66bfefe47f6c84c"`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP CONSTRAINT "FK_fec02639ae24944c2122230ae4c"`);

        // ── Step 2: Drop the spurious camelCase columns ──

        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP COLUMN "promotionId"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "technicianId"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "discountCodeId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP COLUMN "purchaseInvoiceId"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP COLUMN "treatmentCourseId"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP COLUMN "staffId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "technicianId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "repliedByUserId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "invoiceId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP COLUMN "staffId"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP COLUMN "reviewerId"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP COLUMN "invoiceId"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "inventoryItemId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "staffId"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP COLUMN "inventoryItemId"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP COLUMN "updatedByUserId"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "assignedStaffId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "senderUserId"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP COLUMN "assignedUserId"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP COLUMN "bookingId"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP COLUMN "serviceId"`);

        // ── Step 3: Add FK constraints on the correct snake_case columns ──

        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD CONSTRAINT "FK_otp_verifications_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_promotions_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_discount_codes_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_technician_id" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_discount_code_id" FOREIGN KEY ("discount_code_id") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_purchase_invoice_id" FOREIGN KEY ("purchase_invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_treatment_course_id" FOREIGN KEY ("treatment_course_id") REFERENCES "treatment_courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_technician_id" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_replied_by" FOREIGN KEY ("replied_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_inventory_item_id" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_branch_inventory_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_branch_inventory_inventory_item_id" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_assigned_staff_id" FOREIGN KEY ("assigned_staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_conversation_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_sender_user_id" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_assigned_to" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_branch_staff_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_branch_staff_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD CONSTRAINT "FK_branch_opening_hours_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD CONSTRAINT "FK_booking_slot_configs_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_booking_services_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_booking_services_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // ── Step 1: Drop FK constraints on snake_case columns ──

        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_booking_services_service_id"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_booking_services_booking_id"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP CONSTRAINT "FK_booking_slot_configs_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP CONSTRAINT "FK_branch_opening_hours_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_branch_staff_user_id"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_branch_staff_branch_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_assigned_to"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_booking_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_branch_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_customer_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_sender_user_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_conversation_id"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_assigned_staff_id"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_branch_id"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_customer_id"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_updated_by"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_created_by"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_branch_id"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_customer_id"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_branch_inventory_inventory_item_id"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_branch_inventory_branch_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_created_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_staff_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_service_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_booking_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_inventory_item_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_branch_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_service_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_branch_id"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_staff_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_branch_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_customer_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_booking_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_replied_by"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_technician_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_branch_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_service_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_booking_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_customer_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_staff_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_service_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_booking_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_treatment_course_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_purchase_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_branch_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_service_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_customer_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_branch_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_customer_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_booking_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_discount_code_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_technician_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_branch_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_customer_id"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_discount_codes_promotion_id"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_promotions_branch_id"`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP CONSTRAINT "FK_otp_verifications_user_id"`);

        // ── Step 2: Re-add the spurious camelCase columns ──

        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD "promotionId" bigint`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "technicianId" bigint`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "discountCodeId" bigint`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD "purchaseInvoiceId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD "treatmentCourseId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD "staffId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "technicianId" bigint`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "repliedByUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "invoiceId" bigint`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD "staffId" bigint`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD "reviewerId" bigint`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD "invoiceId" bigint`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "inventoryItemId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "staffId" bigint`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "createdByUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD "inventoryItemId" bigint`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD "createdByUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD "updatedByUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "assignedStaffId" bigint`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "conversationId" bigint`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "senderUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD "customerId" bigint`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD "assignedUserId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD "branchId" bigint`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD "bookingId" bigint`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD "serviceId" bigint`);

        // ── Step 3: Re-add FK constraints on the camelCase columns ──

        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD CONSTRAINT "FK_fec02639ae24944c2122230ae4c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_f0c22277696f66bfefe47f6c84c" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_901a674605520b862ab90d4e291" FOREIGN KEY ("promotionId") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_67b9cd20f987fc6dc70f7cd283f" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64de318a01c502530b1e32692fd" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0004f78587144778e6594453737" FOREIGN KEY ("technicianId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_6163d5bf8de921b15bd88c0a4b1" FOREIGN KEY ("discountCodeId") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_eca01fda44679cc1c342822e01b" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_cc476907858590c95b285c1eeb8" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_28850a5ffe7a43c4a584fb0c751" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_70072135e60ecccce7e23630a0e" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_147a11ecdcf0d0fa523a2f195d5" FOREIGN KEY ("purchaseInvoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_627678e9a2a3ac157d5bcbe62e9" FOREIGN KEY ("treatmentCourseId") REFERENCES "treatment_courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_77630101d477abe99bced10fe07" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_6840e49db66ab441fd35ca76f2e" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_a1a11c710e26dd1d28becc355f9" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6d99bdfa69280ede313699fab92" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9563540c43639a0669f68e8ebe3" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_dcb5f7aa1bf056a73208733ce79" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c54130ec9165473fccdde38b77d" FOREIGN KEY ("technicianId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a9c849393e14bd7bde111a833f1" FOREIGN KEY ("repliedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_824be6feda5e655c49c4e0c534b" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_827d04dd3e917e88271d43e664b" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_b430b694818883cea5b8f9938de" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_6508dbe7e688da45f65891652c9" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_1efcd05ef30e6f492c31538e8e2" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_e8af4023b5bfefa942b83773cbb" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_8b7abfe15fc668ef7c251b14aac" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_4db761e1d6856cadc6f523b955d" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_0cff72bb05e6063ed8f06036af4" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_09acaaef552e6fbc1987676f5df" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_af69bc0caf9302582f7930b6547" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_05ae66836bda06ca1048e696d01" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_58844b23b9aefcb7ec2bc2863dc" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_2506f1cb7997e171e2ff1042dcb" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_b239989be631aac1fec54463db8" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_11ef1fb7d5b79c48c712e801c13" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_459d7c3ebd2d350cb2258dd49f4" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_358993f269a7b0c336ebca6f562" FOREIGN KEY ("updatedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_5a4866f304edf4591ad785d34a4" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_36a177d087ea05c7eb5cf618da2" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_7e00ff5bf38a3c03faea05a9d7c" FOREIGN KEY ("assignedStaffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2868049bbe999cdf09aed764400" FOREIGN KEY ("senderUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_3860fae46824a024252a3875769" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_2f071ace1c076ef1c0bc55b1d46" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_4382543bfea88b0b8cb2fa13372" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_4c5b92dda61206dd793e4376a9e" FOREIGN KEY ("assignedUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_3c563aa16f6c0d2807f80f6eb0f" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_a641cc2cf997b72d86e73f0fff8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD CONSTRAINT "FK_cb752f90241fb5cdd151be092ee" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD CONSTRAINT "FK_597fe37979414942a48526a9dbc" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_9a9d697fbd86c5285ed1662c7c7" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_6670d3e3d8c010bcdc3bc7a4be2" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }
}