import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAiInvocationLogs1783871767712 implements MigrationInterface {
    name = 'AddAiInvocationLogs1783871767712'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP CONSTRAINT "FK_otp_verifications_user_id"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_promotions_branch_id"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_discount_codes_promotion_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_customer_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_branch_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_technician_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_discount_code_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_booking_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_customer_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_branch_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_customer_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_service_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_branch_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_treatment_courses_purchase_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_treatment_course_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_booking_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_service_id"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_treatment_sessions_staff_id"`);
        await queryRunner.query(`ALTER TABLE "strategies" DROP CONSTRAINT "FK_strategies_created_by"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_staff_id"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_branch_id"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_schedule_requests_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_staff_schedules_staff"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_staff_schedules_branch"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_staff_schedules_source_request"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_staff_schedules_created_by"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_customer_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_booking_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_service_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_branch_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_technician_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_replied_by"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_booking_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_customer_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_branch_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_invoice_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_service_id"`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" DROP CONSTRAINT "FK_loyalty_accounts_customer"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_loyalty_transactions_account"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_loyalty_transactions_customer"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_loyalty_transactions_booking"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_loyalty_transactions_payment"`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" DROP CONSTRAINT "FK_service_inventory_requirements_service"`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" DROP CONSTRAINT "FK_service_inventory_requirements_item"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_branch_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_inventory_item_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_booking_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_service_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_staff_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_inventory_transactions_created_by"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_branch_inventory_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_branch_inventory_inventory_item_id"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_customer_id"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_branch_id"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_created_by"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_health_records_updated_by"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_customer_id"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_branch_id"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_conversations_assigned_staff_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_conversation_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_sender_user_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_customer_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_branch_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_booking_id"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_assigned_to"`);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP CONSTRAINT "FK_0d09eb026d1cafd3e5177d8deba"`);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP CONSTRAINT "FK_162b14b5d05c0698b6a12c6fff6"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_branch_staff_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_branch_staff_user_id"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP CONSTRAINT "FK_branch_opening_hours_branch_id"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP CONSTRAINT "FK_booking_slot_configs_branch_id"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_booking_services_booking_id"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_booking_services_service_id"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_payment_tx_booking"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_payment_tx_branch"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_payment_tx_customer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_treatment_sessions_next_recommended_at"`);
        await queryRunner.query(`ALTER TABLE "branch_daily_aggregates" DROP CONSTRAINT "UQ_bda_branch_date"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "UQ_payment_tx_booking_deposit"`);
        await queryRunner.query(`CREATE TABLE "ai_invocation_logs" ("id" BIGSERIAL NOT NULL, "feature" character varying(50) NOT NULL, "user_id" bigint, "branch_id" bigint, "model" character varying(50) NOT NULL, "prompt_tokens" integer NOT NULL DEFAULT '0', "completion_tokens" integer NOT NULL DEFAULT '0', "estimated_cost_usd" numeric(10,6) NOT NULL DEFAULT '0', "success" boolean NOT NULL DEFAULT true, "error_message" text, "latency_ms" integer NOT NULL DEFAULT '0', "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_caf7e39913d7578520a45839cf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ai_invocation_logs_created_at" ON "ai_invocation_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ai_invocation_logs_user_id" ON "ai_invocation_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ai_invocation_logs_feature" ON "ai_invocation_logs" ("feature") `);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP COLUMN "serviceId"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bda_branch_date" ON "branch_daily_aggregates" ("branch_id", "aggregate_date") `);
        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD CONSTRAINT "FK_c7f1d281e1acc51e2a37889f5a9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_7f080aa23bcb8ef34da69d36896" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_fb4703590234d38dc1a0a79f2ae" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_2fd4b38fce271ea8c4df10b411b" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_dc6c4a78acd72271f451f732bfa" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_6975569310ee1bde99b2072c4cf" FOREIGN KEY ("discount_code_id") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_089eb569dbd0fc95559bb12f360" FOREIGN KEY ("transferred_from_branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_322e045cc9ee0a9ff20dd8337ec" FOREIGN KEY ("rescheduled_from_booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_44342bfa812465df91df3d9a152" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ed9c7aa7846704bbcb648377e8f" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_f8b468df52fb45053ad0c4ca38b" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_d706a7a7ca03991b07191f6ec5f" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_e897bebb223a7f19ab962a7f8bb" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_f05df4f961bb42e351d3cf4c399" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_e718d01463629cc093be8a8d569" FOREIGN KEY ("purchase_invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_e45c80f881993d157e550d78828" FOREIGN KEY ("treatment_course_id") REFERENCES "treatment_courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_29ecb93c9dbcf406d9c78781d91" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_2ebb8f1f7a8d042c0c52bf1ae91" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_a837c8444ef96f3cadca075bb8a" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "strategies" ADD CONSTRAINT "FK_0118cd40c3be6124f2d5f8ad3c4" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_ce0ea6fea0e5adbba7ded32f87b" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_0499286c8edaf2190349ccc3328" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_1b2704c0970942a28baaed9af70" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_7e5a137a3496008f8b164e7c477" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_d3e78a198f9296c95a54531b7ea" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_4f340091a5380f1a8e29524f537" FOREIGN KEY ("source_request_id") REFERENCES "schedule_requests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_684d0d34cb55be73e5200d4dd4a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_6587db79174d07150fde1f1a4d6" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_f75b369d2d9c423c8118f62fdd3" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_e4f847330bb3d2fa17888e10564" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_36a464591a8b296db974ca6a1de" FOREIGN KEY ("replied_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b50ef2c264e6c0fda8c639935af" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_addd19c06574aa904472b8c82bd" FOREIGN KEY ("received_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_223971a01d0fbc9354854867b40" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "FK_1c7eaf158aad7e4a839232cc9ba" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_291582ddb64e1afc56f2c51ac7e" FOREIGN KEY ("account_id") REFERENCES "loyalty_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_39f39219f9587d34638ccde8b67" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_a51f0b10d0baf1f83b89cb8b2bc" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_4f0444a5902078dcd9f96373c5c" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" ADD CONSTRAINT "FK_2138adad4d5063fc2dca4da5788" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" ADD CONSTRAINT "FK_3bfaaa94225ef290e76c206f640" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_d387567f1f55c4d1445548ed34f" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_e72ff3d54aa54059dbd70c41ee9" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_8a1555869d2c83e31f4c0aca158" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_ecb0ff1967f2116f2ce131c7255" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_4a835dfe7515222333ca7393ca4" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_d9a2ac973b889087b33f84d3517" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_6cd826d26d62acf07e7ae226f75" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_403e95dc466f332f81448500252" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_cf3d8bb564e2e20be9deadccdaf" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_4b5e1578fc204a10af395691a63" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_40de330638d6377f2ac674d7d7f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_0994135d986124a0215d9970aa6" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_c9f0434c15cacf894e996f69088" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_702c7b782a1a9cc00d2053f059c" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_0a2ed55d1eafc3a117a9076f6bf" FOREIGN KEY ("assigned_staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_b183972e0b84c9022884433195e" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_de3bcf476dd0a829679018caa63" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_ea1eb29f62e0a62102ee6dbb190" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_a56fb6611928c35f52a13bd4751" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_7444fe5ccbbc0e09cc462f3895a" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD CONSTRAINT "FK_a6d74e5a895f47319cb53f64994" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD CONSTRAINT "FK_5302ae06d739d97496ffca2d091" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_35e3d0e075849f166c9e90b6420" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_92027293936870abd797452939f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD CONSTRAINT "FK_9c0db57549f0c96ae1faf803cd4" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD CONSTRAINT "FK_41274dedbe25326f23e50dd4a1b" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_6e853453a3c24df1beed35c13eb" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_614f93092163be95d794fb4ead1" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_ece2cd696ed7e3d769047a4c73b" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_b6629510f01ed862de48c228fe3" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_b6629510f01ed862de48c228fe3"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_ece2cd696ed7e3d769047a4c73b"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_614f93092163be95d794fb4ead1"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_6e853453a3c24df1beed35c13eb"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6"`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" DROP CONSTRAINT "FK_41274dedbe25326f23e50dd4a1b"`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" DROP CONSTRAINT "FK_9c0db57549f0c96ae1faf803cd4"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_92027293936870abd797452939f"`);
        await queryRunner.query(`ALTER TABLE "branch_staff" DROP CONSTRAINT "FK_35e3d0e075849f166c9e90b6420"`);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP CONSTRAINT "FK_5302ae06d739d97496ffca2d091"`);
        await queryRunner.query(`ALTER TABLE "branch_services" DROP CONSTRAINT "FK_a6d74e5a895f47319cb53f64994"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_7444fe5ccbbc0e09cc462f3895a"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_a56fb6611928c35f52a13bd4751"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_ea1eb29f62e0a62102ee6dbb190"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_de3bcf476dd0a829679018caa63"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_b183972e0b84c9022884433195e"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_0a2ed55d1eafc3a117a9076f6bf"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_702c7b782a1a9cc00d2053f059c"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_c9f0434c15cacf894e996f69088"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_0994135d986124a0215d9970aa6"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_40de330638d6377f2ac674d7d7f"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_4b5e1578fc204a10af395691a63"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_cf3d8bb564e2e20be9deadccdaf"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_403e95dc466f332f81448500252"`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" DROP CONSTRAINT "FK_6cd826d26d62acf07e7ae226f75"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_d9a2ac973b889087b33f84d3517"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_4a835dfe7515222333ca7393ca4"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_ecb0ff1967f2116f2ce131c7255"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_8a1555869d2c83e31f4c0aca158"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_e72ff3d54aa54059dbd70c41ee9"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_d387567f1f55c4d1445548ed34f"`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" DROP CONSTRAINT "FK_3bfaaa94225ef290e76c206f640"`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" DROP CONSTRAINT "FK_2138adad4d5063fc2dca4da5788"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_4f0444a5902078dcd9f96373c5c"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_a51f0b10d0baf1f83b89cb8b2bc"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_39f39219f9587d34638ccde8b67"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_291582ddb64e1afc56f2c51ac7e"`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" DROP CONSTRAINT "FK_1c7eaf158aad7e4a839232cc9ba"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_223971a01d0fbc9354854867b40"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_addd19c06574aa904472b8c82bd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b50ef2c264e6c0fda8c639935af"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_36a464591a8b296db974ca6a1de"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_e4f847330bb3d2fa17888e10564"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_f75b369d2d9c423c8118f62fdd3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_6587db79174d07150fde1f1a4d6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_684d0d34cb55be73e5200d4dd4a"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_4f340091a5380f1a8e29524f537"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_d3e78a198f9296c95a54531b7ea"`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" DROP CONSTRAINT "FK_7e5a137a3496008f8b164e7c477"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_1b2704c0970942a28baaed9af70"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_0499286c8edaf2190349ccc3328"`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" DROP CONSTRAINT "FK_ce0ea6fea0e5adbba7ded32f87b"`);
        await queryRunner.query(`ALTER TABLE "strategies" DROP CONSTRAINT "FK_0118cd40c3be6124f2d5f8ad3c4"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_a837c8444ef96f3cadca075bb8a"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_2ebb8f1f7a8d042c0c52bf1ae91"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_29ecb93c9dbcf406d9c78781d91"`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" DROP CONSTRAINT "FK_e45c80f881993d157e550d78828"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_e718d01463629cc093be8a8d569"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_f05df4f961bb42e351d3cf4c399"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_e897bebb223a7f19ab962a7f8bb"`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" DROP CONSTRAINT "FK_d706a7a7ca03991b07191f6ec5f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_f8b468df52fb45053ad0c4ca38b"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ed9c7aa7846704bbcb648377e8f"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_44342bfa812465df91df3d9a152"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_322e045cc9ee0a9ff20dd8337ec"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_089eb569dbd0fc95559bb12f360"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_6975569310ee1bde99b2072c4cf"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_dc6c4a78acd72271f451f732bfa"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_2fd4b38fce271ea8c4df10b411b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_fb4703590234d38dc1a0a79f2ae"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_7f080aa23bcb8ef34da69d36896"`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" DROP CONSTRAINT "FK_c7f1d281e1acc51e2a37889f5a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bda_branch_date"`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD "branchId" bigint`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ai_invocation_logs_feature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ai_invocation_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ai_invocation_logs_created_at"`);
        await queryRunner.query(`DROP TABLE "ai_invocation_logs"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "UQ_payment_tx_booking_deposit" UNIQUE ("booking_id", "transaction_type")`);
        await queryRunner.query(`ALTER TABLE "branch_daily_aggregates" ADD CONSTRAINT "UQ_bda_branch_date" UNIQUE ("branch_id", "aggregate_date")`);
        await queryRunner.query(`CREATE INDEX "IDX_treatment_sessions_next_recommended_at" ON "treatment_sessions" ("next_recommended_at") `);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_payment_tx_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_payment_tx_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_payment_tx_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_booking_services_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_booking_services_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_slot_configs" ADD CONSTRAINT "FK_booking_slot_configs_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_opening_hours" ADD CONSTRAINT "FK_branch_opening_hours_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_branch_staff_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_staff" ADD CONSTRAINT "FK_branch_staff_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD CONSTRAINT "FK_162b14b5d05c0698b6a12c6fff6" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_services" ADD CONSTRAINT "FK_0d09eb026d1cafd3e5177d8deba" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_assigned_to" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_sender_user_id" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_conversation_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_assigned_staff_id" FOREIGN KEY ("assigned_staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_conversations_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_health_records_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_branch_inventory_inventory_item_id" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_inventory" ADD CONSTRAINT "FK_branch_inventory_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_inventory_item_id" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_inventory_transactions_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" ADD CONSTRAINT "FK_service_inventory_requirements_item" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_inventory_requirements" ADD CONSTRAINT "FK_service_inventory_requirements_service" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_loyalty_transactions_payment" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_loyalty_transactions_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_loyalty_transactions_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_loyalty_transactions_account" FOREIGN KEY ("account_id") REFERENCES "loyalty_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "FK_loyalty_accounts_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_replied_by" FOREIGN KEY ("replied_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_technician_id" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_staff_schedules_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_staff_schedules_source_request" FOREIGN KEY ("source_request_id") REFERENCES "schedule_requests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_staff_schedules_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_schedules" ADD CONSTRAINT "FK_staff_schedules_staff" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_requests" ADD CONSTRAINT "FK_schedule_requests_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "strategies" ADD CONSTRAINT "FK_strategies_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_staff_id" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_sessions" ADD CONSTRAINT "FK_treatment_sessions_treatment_course_id" FOREIGN KEY ("treatment_course_id") REFERENCES "treatment_courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_purchase_invoice_id" FOREIGN KEY ("purchase_invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_service_id" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_courses" ADD CONSTRAINT "FK_treatment_courses_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_booking_id" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_discount_code_id" FOREIGN KEY ("discount_code_id") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_technician_id" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_customer_id" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_discount_codes_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_promotions_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp_verifications" ADD CONSTRAINT "FK_otp_verifications_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
