export const ERROR_CODES = {
  STAFF_BUSY: 'STAFF_BUSY',
  CUSTOMER_HAS_BOOKING: 'CUSTOMER_HAS_BOOKING',
  EXCEEDS_OPERATING_HOURS: 'EXCEEDS_OPERATING_HOURS',
  BRANCH_CLOSED: 'BRANCH_CLOSED',
  BOOKING_TOO_SOON: 'BOOKING_TOO_SOON',
  BOOKING_TOO_FAR: 'BOOKING_TOO_FAR',
  STAFF_NO_SKILL: 'STAFF_NO_SKILL',
  SERVICE_NOT_AT_BRANCH: 'SERVICE_NOT_AT_BRANCH',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_NOT_TRANSFERABLE: 'BOOKING_NOT_TRANSFERABLE',
  SLOT_CONFLICT_AT_TARGET: 'SLOT_CONFLICT_AT_TARGET',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE', // suspended or deleted account tries to log in
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION', // unverified account tries to log in
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS', // register with duplicate email
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS', // register/update with duplicate phone
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  OTP_INVALID: 'OTP_INVALID', // wrong OTP code submitted
  OTP_EXPIRED: 'OTP_EXPIRED', // OTP TTL elapsed
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS', // too many failed attempts
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ErrorCodeGroup {
  domain: 'booking' | 'auth' | 'common';
  codes: readonly ErrorCode[];
}

export const ERROR_CODE_GROUPS: readonly ErrorCodeGroup[] = [
  {
    domain: 'booking',
    codes: [
      ERROR_CODES.STAFF_BUSY,
      ERROR_CODES.CUSTOMER_HAS_BOOKING,
      ERROR_CODES.EXCEEDS_OPERATING_HOURS,
      ERROR_CODES.BRANCH_CLOSED,
      ERROR_CODES.BOOKING_TOO_SOON,
      ERROR_CODES.BOOKING_TOO_FAR,
      ERROR_CODES.STAFF_NO_SKILL,
      ERROR_CODES.SERVICE_NOT_AT_BRANCH,
      ERROR_CODES.INVALID_STATUS_TRANSITION,
      ERROR_CODES.BOOKING_NOT_CANCELLABLE,
      ERROR_CODES.BOOKING_NOT_TRANSFERABLE,
      ERROR_CODES.SLOT_CONFLICT_AT_TARGET,
    ],
  },
  {
    domain: 'auth',
    codes: [
      ERROR_CODES.INVALID_CREDENTIALS,
      ERROR_CODES.ACCOUNT_INACTIVE,
      ERROR_CODES.ACCOUNT_PENDING_VERIFICATION,
      ERROR_CODES.EMAIL_ALREADY_EXISTS,
      ERROR_CODES.PHONE_ALREADY_EXISTS,
      ERROR_CODES.TOKEN_EXPIRED,
      ERROR_CODES.TOKEN_INVALID,
      ERROR_CODES.OTP_INVALID,
      ERROR_CODES.OTP_EXPIRED,
      ERROR_CODES.OTP_MAX_ATTEMPTS,
    ],
  },
  {
    domain: 'common',
    codes: [ERROR_CODES.NOT_FOUND, ERROR_CODES.FORBIDDEN, ERROR_CODES.VALIDATION_ERROR, ERROR_CODES.INTERNAL_SERVER_ERROR],
  },
];
